# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f70be2bb81cfc1409efe3fdc741061d66085e293e2386aea3ded061e14bd94b49129412f635c577d649b8591e3aed51da3d8b501b3e5d587c2afb381a0224c23

test:
  secret_key_base: 16f7ad6bb35f683f50dd07b44a0b84cc7f179f67c3c5ae8d31f6d68bf6b939c9904bb8b47d59eb2882b2a5c2a1c527c00eef4c15d0b15c674cc19dd81b281ae3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
